#!/usr/bin/env bash
#
# Compile and run a project
#
# Dependencies:
#   - gcc
#
# Author: Jesse Mirabel <sejjymvm@gmail.com>
# Date:   September 08, 2026

fatal() {
	local script=${0##*/}

	echo "$script: $*" >&2
	exit 1
}

main() {
	if (($# != 2)); then
		fatal "<chapter> <project>"
	fi

	local c=$((10#$1))
	local p=$((10#$2))

	if ((c < 2 || c > 27)); then
		fatal "chapter must be 02 to 27"
	fi

	if ((p < 1 || p > 19)); then
		fatal "project must be 01 to 19"
	fi

	printf -v c "%02d" "$c"
	printf -v p "%02d" "$p"

	local bin proj

	case $PWD in
		*/c-projects/*/bin)
			bin="."
			proj="../$p.c"
			;;
		*/c-projects/*)
			bin="./bin"
			proj="./$p.c"
			;;
		*/c-projects)
			bin="./$c/bin"
			proj="./$c/$p.c"
			;;
		*)
			fatal "must be run from the c-projects root directory"
			;;
	esac

	if [[ ! -d $bin ]]; then
		mkdir -p "$bin"
	fi

	gcc -O -Wall -W -pedantic -ansi -std=c99 -o "$bin/$p" "$proj" && "$bin/$p"
}

main "$@"
