#!/usr/bin/env bash
#
# Compile and run a project
#
# Dependencies:
#   - gcc
#
# Author: Jesse Mirabel <sejjymvm@gmail.com>
# Date:   September 08, 2026

fatal() {
	local script=${0##*/}

	echo "$script: $*" >&2
	exit 1
}

main() {
	if (($# < 2)); then
		fatal "<chapter> <project> [args...]"
	fi

	local chapter=$((10#$1))
	local project=$((10#$2))
	local args=("${@:3}")

	if ((chapter < 2 || chapter > 27)); then
		fatal "chapter must be 2 to 27"
	fi

	if ((project < 1 || project > 19)); then
		fatal "project must be 1 to 19"
	fi

	printf -v chapter "%02d" "$chapter"
	printf -v project "%02d" "$project"

	local workdir=${PWD##*/}
	local chapdir="./$chapter"

	if [[ $workdir == "$chapter" ]]; then
		chapdir="."
	fi

	local infile outfile

	if ((10#$chapter < 15)); then
		infile="$chapdir/$project.c"
		outfile="$chapdir/$project"
	else
		infile="$chapdir/$project/main.c"
		outfile="$chapdir/$project/main"
	fi

	# shellcheck disable=SC2064
	trap "rm -f $outfile" EXIT

	gcc -O -Wall -W -pedantic -ansi -std=c99 -o "$outfile" "$infile" &&
		"$outfile" "${args[@]}"
}

main "$@"
